language: java
sudo: false
branches:
  only:
    # Only build (and deploy) pushes tagged with a version number
    - /^v2.*$/
env:
  global:
    secure: dGzZ9hl0ezUCYs72+Z4LUgtny0qsUn3HibpBKo4hriRPMY8EQqaJfi1ZDQTKr3ctjJMtQtcgnlC0BujEV+1W2tObjSJsCAdEbzKYZijwRXSK5jT1sua3EQScKYelpv0z4fd9LIYJJ95xwXMNMmAFSjdu3fRDkxtGgIIKbka8YiE=
notifications:
  email: false
before_install:
  # Change the maven-version to be the tag (for the API deploy)
  # Skip the 'v'
  - mvn versions:set -Dtravis.buildNumber=${TRAVIS_BUILD_NUMBER} -DnewVersion=${TRAVIS_TAG:1}
install: true
script:
  - mvn -nsu -Dtravis.buildNumber=${TRAVIS_BUILD_NUMBER} -DGITHUB_TOKEN=${GITHUB_TOKEN} -Pi18n,shadeGuava,-1.8,1.7.9 deploy
deploy:
  provider: releases
  api-key: ${GITHUB_TOKEN}
  file:
  - uSkyBlock-Plugin/target/uSkyBlock.jar
  - uSkyBlock-API/target/uSkyBlock-API.jar
  - uSkyBlock-Plugin/target/uSkyBlock-Plugin/gettext-report.txt
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
cache:
  directories:
  - $HOME/.m2
